### ISSUE TITLE
Unexpectedly high price

### ISSUE THREAD

**Issue by madvas** [ether-camp/oraclize-example#1]
I followed your instructions, but my code always stops on price condition. Don't you know why this is?

This is snippet from `oraclizeAPI.sol`. code can't get thru the condition. I did exactly as in instructions. 

```
function oraclize_query(uint timestamp, string datasource, string arg) oraclizeAPI internal returns (bytes32 id){
        uint price = oraclize.getPrice(datasource);
        if (price > 1 ether + tx.gasprice*200000) {
            log0("unexpectedly high price");
            return 0; // unexpectedly high price
        }
        if (price > this.balance) log2("oraclize", "oraclize_error", "not_enough_funds");
        else return oraclize.query.value(price)(timestamp, datasource, arg);
    }
```

Thanks,
Matus

**Comment by romanman** [comment]
We are checking that. 

@asinyagin

**Comment by asinyagin** [comment]
@madvas thanks for the report. We have an error in our compiler lib, it treats a new solc warning as an error and doesn't compile oraclize contract. We plan to update IDE tomorrow with the fix. There's no workaround, so I'll fix your IDE manually today.

**Comment by madvas** [comment]
thanks for your great effort! no need to hurry, it's okay for me tomorrow ;)
